name: Hello World CI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # <-- Manual trigger added

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
